### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by dosanjhkiran** [dosanjhkiran/weather_dashboard#1]
##User Story
As a User,
I want the webpage to have a clear and semantic HTML structure,
So that the content is easy to navigate and accessible.

Acceptance Criteria
GIVEN the index.html file,
WHEN I view the HTML structure,
THEN I can see semantic elements such as header, main, section, and footer.
AND I can see placeholders for current weather, five-day forecast, and search functionality.

**Comment by ANAZ0004** [comment]
Addressed in latest pull request.
