### ISSUE TITLE
Implement a stylised CSS file.

### ISSUE THREAD

**Issue by dosanjhkiran** [dosanjhkiran/weather_dashboard#2]
## User Story
As a User
I want the webpage to be styled with CSS,
So that it looks visually appealing and provides a good user experience.

## Acceptance Criteria

- GIVEN the CSS file,
- WHEN I view the webpage,
- THEN I can see a well-styled layout with consistent fonts, colors, and spacing.
- AND the webpage should include styles for:
- Header and navigation
- Current weather section
- Five-day forecast section
- Search bar
- Footer
- GIVEN the header and navigation,
- WHEN I view the webpage,
- THEN I can see a styled header with a clear title and navigation links.
- AND the header should have a background color, appropriate padding, and font styles.'
- GIVEN the current weather section,
- WHEN I view the webpage,
- THEN I can see a styled section with temperature, humidity, wind speed, and weather description.
- AND the section should include an appropriate layout, spacing, and weather icon.

**Comment by ANAZ0004** [comment]
Addressed in latest pull request.
