### ISSUE TITLE
JavaScript fetches data from API

### ISSUE THREAD

**Issue by dosanjhkiran** [dosanjhkiran/weather_dashboard#3]
### User Story
As a User,
I want to fetch and display the current weather data for a default location,
So that I can see how the JavaScript interacts with the weather API.

## Acceptance Criteria
GIVEN the JavaScript file,
WHEN the page loads,
THEN the script fetches current weather data from the API for a default location.
AND the weather data is displayed on the webpage (temperature, humidity, wind speed, and weather description.
GIVEN the search bar on the webpage,
WHEN I enter a city name or ZIP code and submit the form,
THEN the script fetches weather data for the specified location.
AND the weather data is displayed on the webpage.

**Comment by ANAZ0004** [comment]
Addressed in latest pull request.
