### ISSUE TITLE
Use icons to represent weather conditions.

### ISSUE THREAD

**Issue by dosanjhkiran** [dosanjhkiran/weather_dashboard#4]
## User Story
As a user,
I want to see weather icons representing the current weather and forecast,
So that I can quickly understand the weather conditions.

## Acceptance Criteria
GIVEN the weather data fetched from the API,
WHEN the data includes weather conditions,
THEN the corresponding weather icons are displayed on the webpage.
AND the icons are accurate and visually representative of the weather conditions.

**Comment by ANAZ0004** [comment]
[For future reference.](https://openweathermap.org/weather-conditions)
